spring:
  mail:
    host: email
    port: 1
    username: 1
    password: 1
    properties:
     mail:
      smtp:
        auth: true
        starttls:
          enable: false
        ssl:
          enable: true
  application:
    name: tlias
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 1
    username: 1
    password: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    session:
      timeout: 1800s # 30分钟
    context-path: /api
aliyun:
  oss:
    accessKeyId: 1
    endpoint: 1
    accessKeySecret: 1
    bucketName: 1
#spring事务开关
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.security: DEBUG



